// <auto-generated />
namespace C4DEnterpriseSys_ver1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addstringelse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addstringelse));
        
        string IMigrationMetadata.Id
        {
            get { return "201904211504197_addstringelse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
