// <auto-generated />
namespace C4DEnterpriseSys_ver1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addsth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addsth));
        
        string IMigrationMetadata.Id
        {
            get { return "201903061419561_addsth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
